package com.paymentproof.entity.enums;

public enum IncidentType {
    DELAYED_CONFIRMATION,
    BANK_DEBIT_GATEWAY_FAILURE,
    GATEWAY_SUCCESS_MISSING_WEBHOOK,
    DUPLICATE_PAYMENT,
    REFUND_UNCERTAINTY,
    SETTLEMENT_MISMATCH,
    MERCHANT_CANCELLATION_BEFORE_CONFIRMATION,
    CONFLICTING_PAYMENT_STATES,
    NORMAL_PAYMENT_FALSE_ALARM,
    GENUINELY_UNRESOLVED_CASE
}
