package com.paymentproof.entity.enums;

public enum ResolutionAction {
    CUSTOMER_REFUNDED,
    MERCHANT_CREDITED,
    WEBHOOK_RESENT_AND_FULFILLED,
    DUPLICATE_REVERSED,
    TRANSACTION_SETTLED_MANUALLY,
    NO_DISCREPANCY_FOUND,
    ESCALATED_LEGAL_COMPLIANCE
}
